{
  # Harbor — Foundation F3: Fail-Closed Hermetic Toolchain (the pinning half).
  #
  # This flake provides a dev shell with EXACTLY the toolchain every Harbor
  # check needs, pinned to one nixpkgs revision so every agent, every human, and
  # CI run the identical tool versions. Combined with the fail-closed Makefile
  # (the other half of F3), this makes "green means green" true everywhere:
  #
  #   local:  nix develop -c make agent-check
  #   CI:     nix develop -c make agent-check   (.github/workflows/ci.yml)
  #
  # Because the Makefile FAILS CLOSED on a missing tool (a skipped check that
  # passes is a lie to the agent), the whole point of this shell is to guarantee
  # the tools are present and identical — so the checks actually run.
  #
  # `flake.lock` is generated by `nix flake update` (do NOT hand-write it); it
  # freezes the nixpkgs revision that pins the versions below.
  description = "Harbor — pinned, hermetic developer toolchain (Foundation F3)";

  inputs = {
    # Pinned to a stable channel; `nix flake update` refreshes flake.lock.
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.05";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };

        # go.mod declares `go 1.25.0` (required by grpc v1.82+, webauthn v0.17+,
        # pgx v5.10+, golang.org/x/* v0.52+). The nix shell provides go_1_24 as
        # a bootstrap; GOTOOLCHAIN=auto (Go default since 1.21) auto-downloads
        # go1.25.0 when the build or test commands need it. Prefer go_1_25 once
        # nixpkgs 25.05 ships that attribute; until then the fallback is go_1_24.
        goToolchain = pkgs.go_1_25 or pkgs.go_1_24 or pkgs.go;

        # nixpkgs' `golangci-lint` is compiled with whatever `go` was the
        # channel default at packaging time — currently go1.24, one minor
        # behind go.mod's `go 1.25.0`. golangci-lint v2 refuses to analyze a
        # module whose go directive exceeds its own compile-time Go version
        # ("the Go language version go1.24 used to build golangci-lint is
        # lower than the targeted Go version 1.25.0"), and there is no config
        # workaround: forcing a lower `run.go` just moves the failure into a
        # go/types crash instead (file versions still propagate from go.mod).
        # Fix: rebuild golangci-lint from the SAME nixpkgs source against
        # `goToolchain` via an overlay — `vendorHash` only hashes vendored Go
        # source, so it is unaffected by the compiler version. Drop this
        # override once nixpkgs' `golangci-lint` is itself built with go1.25+.
        pkgsWithLintGo = pkgs.extend (_: _: { go = goToolchain; });
        golangciLint = pkgsWithLintGo.golangci-lint;

        # The pinned toolchain — one list, mirrored by the Makefile's install
        # hints. Every tool the fail-closed Makefile requires lives here.
        toolchain = [
          goToolchain
          golangciLint                  # @validate: lint (rebuilt with goToolchain, see above)
          pkgs.sqlc                     # @codegen: sqlc generate
          pkgs.oapi-codegen             # @codegen: OpenAPI -> Go stubs
          pkgs.buf                      # @codegen/@validate: proto gen + lint
          pkgs.go-migrate               # @db-migrate: schema migrations (`migrate`) — nixpkgs renamed golang-migrate -> go-migrate
          pkgs.k6                       # @load-test: hot-path load tests
          pkgs.nodejs                   # web codegen runtime (also Node>=20.19 for openspec)
          pkgs.pnpm                     # @codegen: pnpm codegen (web client)
          pkgs.python3                  # @docs: docs-check scripts (check-design-refs / check-doc-links)
        ];

        # OPTIONAL, resilient tools — on PATH when the channel provides them,
        # but a missing attribute must NEVER hard-break `nix develop`. openspec
        # is skill-only (NOT a gating agent-check tool yet) and @fission-ai/
        # openspec may not be packaged in this channel, so pin it via the
        # `or null` fallback and filter it out when absent (see comment below).
        optionalTools = builtins.filter (p: p != null) [
          (pkgs.openspec or null)       # @openspec: spec-driven dev — provides `openspec` (validate --strict)
          (pkgs.spectral-cli or null)   # spectral OpenAPI linter — REMOVED from nixpkgs; pinned via npx in CI (see below)
        ];
      in
      {
        devShells.default = pkgs.mkShell {
          buildInputs = toolchain ++ optionalTools;

          # spectral (@stoplight/spectral-cli) was REMOVED from nixpkgs (it is no
          # longer available as a Nix package on any channel, incl. unstable), so
          # it can no longer be pinned into this shell. It is now pinned OPTIONALLY
          # via `(pkgs.spectral-cli or null)` in `optionalTools` above (present
          # only if a future channel re-adds it), and the `spectral` binary is NOT
          # guaranteed on PATH inside `nix develop`. Instead the OpenAPI spec-lint
          # runs as a dedicated CI-side step via `npx @stoplight/spectral-cli@6.16.1`
          # (see .github/workflows/ci.yml), and `make validate` uses the same
          # version-pinned npx invocation locally — so the command is identical in
          # both places even though it is no longer part of the pinned shell.
          #
          # openspec (@fission-ai/openspec) is pinned OPTIONALLY via
          # `(pkgs.openspec or null)` in `optionalTools` above — it may not exist
          # in this channel yet, and because openspec is skill-only (NOT a gating
          # agent-check tool), a missing attribute must NOT hard-break
          # `nix develop` (unlike the required tools in `toolchain`). It needs
          # Node>=20.19 (satisfied by `pkgs.nodejs` above) and provides the
          # `openspec` binary (@openspec: spec-driven dev, `validate --strict`).
          # When the attribute is absent, the documented install fallback is the
          # pinned Node's npm: `npm install -g @fission-ai/openspec@latest`
          # (see .agents/openspec.md).
          shellHook = ''
            echo 'Harbor hermetic dev shell — pinned toolchain (flake.nix). Run: make agent-check'
          '';
        };
      });
}
