apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/harbor-auth/harbor.git
    targetRevision: main
    path: deploy/platform
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
