package identity

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"

	"github.com/google/uuid"
	"github.com/harbor-auth/harbor/internal/crypto"
	"github.com/harbor-auth/harbor/internal/gen/db"
	"github.com/jackc/pgx/v5/pgtype"
)

// EventType is a closed set of audit-trail event identifiers (DESIGN §2.1,
// §10). The coarse type is stored in the clear so operators can page/filter
// by category; the sensitive detail is always encrypted under the user's DEK.
type EventType string

const (
	// EventAuthLogin records a successful authentication ceremony.
	EventAuthLogin EventType = "auth.login"
	// EventTokenIssued records the issuance of a new access/ID token pair.
	EventTokenIssued EventType = "token.issued"
	// EventTokenRefreshed records a refresh-token rotation.
	EventTokenRefreshed EventType = "token.refreshed"
	// EventTokenRevoked records a token revocation (RFC 7009 POST /revoke, or
	// a forced revocation triggered by a theft signal).
	EventTokenRevoked EventType = "token.revoked"
	// EventConsentGranted records a user granting consent to an RP.
	EventConsentGranted EventType = "consent.granted"
	// EventConsentScopeEscalated records a scope upgrade on an existing grant.
	EventConsentScopeEscalated EventType = "consent.scope_escalated"
	// EventConsentRevoked records a user revoking consent from an RP.
	EventConsentRevoked EventType = "consent.revoked"

	// EventComplianceExportRequested records a DSAR export request by the
	// authenticated user.
	EventComplianceExportRequested EventType = "compliance.export_requested"
	// EventComplianceEraseRequested records the initiation of a right-to-be-
	// forgotten erasure request by the authenticated user.
	EventComplianceEraseRequested EventType = "compliance.erase_requested"
	// EventComplianceEraseCompleted records the successful crypto-shred
	// erasure of the user's DEK, making all envelope-encrypted PII
	// permanently unrecoverable.
	EventComplianceEraseCompleted EventType = "compliance.erase_completed"
)

// AuditEventInserter is the narrow write interface AuditRecorder needs from
// the DB layer. Satisfied by *db.Queries (generated by sqlc).
type AuditEventInserter interface {
	CreateAuditEvent(ctx context.Context, arg db.CreateAuditEventParams) (db.AuditEvent, error)
	CreateAuditEventWithPayload(ctx context.Context, arg db.CreateAuditEventWithPayloadParams) (db.AuditEvent, error)
}

// AuditUserLoader fetches the minimal user row needed to unwrap the DEK.
// Satisfied by a thin adapter over *db.Queries.GetUser.
type AuditUserLoader interface {
	LoadUserForAudit(ctx context.Context, userID string) (region string, dekWrapped []byte, err error)
}

// AuditRecorder envelope-encrypts each event's detail under the user's DEK
// and appends the row to audit_events. Emission is always best-effort: callers
// must wrap Record in a goroutine (or use RecordAsync) so that a slow/failing
// audit write never stalls the auth hot path (DESIGN §3: Decision 3).
type AuditRecorder struct {
	users  AuditUserLoader
	store  AuditEventInserter
	keys   crypto.KeyProvider
	cipher crypto.Encryptor
	logger *slog.Logger
}

// NewAuditRecorder constructs an AuditRecorder. All arguments must be non-nil.
func NewAuditRecorder(
	users AuditUserLoader,
	store AuditEventInserter,
	keys crypto.KeyProvider,
	cipher crypto.Encryptor,
	logger *slog.Logger,
) *AuditRecorder {
	if logger == nil {
		logger = slog.Default()
	}
	return &AuditRecorder{
		users:  users,
		store:  store,
		keys:   keys,
		cipher: cipher,
		logger: logger,
	}
}

// auditPayloadAAD returns the GCM additional data for a per-event payload.
// Binding the user ID to the AAD means ciphertext written for user A cannot
// pass GCM authentication when read as user B (DESIGN §4.4).
func auditPayloadAAD(userID string) []byte {
	return []byte("harbor-audit-payload-v1:" + userID)
}

// Record encrypts detail under the user's DEK and appends an audit event row.
// detail must be JSON-marshallable. clientID may be empty when no RP context
// is available (e.g. a recovery ceremony that precedes any client binding).
//
// Record is SYNCHRONOUS — callers on the hot path should use RecordAsync
// instead so that a slow audit write never stalls authentication.
func (r *AuditRecorder) Record(ctx context.Context, userID string, et EventType, clientID *string, detail any) error {
	region, dekWrapped, err := r.users.LoadUserForAudit(ctx, userID)
	if err != nil {
		return fmt.Errorf("identity: audit: load user %q: %w", userID, err)
	}

	dek, err := r.keys.UnwrapDEK(ctx, region, dekWrapped)
	if err != nil {
		return fmt.Errorf("identity: audit: unwrap DEK for user %q: %w", userID, err)
	}

	var plaintext []byte
	if detail != nil {
		plaintext, err = json.Marshal(detail)
		if err != nil {
			return fmt.Errorf("identity: audit: marshal detail: %w", err)
		}
	}

	ciphertext, err := r.cipher.Encrypt(dek, plaintext, auditPayloadAAD(userID))
	if err != nil {
		return fmt.Errorf("identity: audit: encrypt payload: %w", err)
	}

	userUUID, err := parseAuditUUID(userID)
	if err != nil {
		return fmt.Errorf("identity: audit: parse user UUID: %w", err)
	}

	eventID := pgtype.UUID{Bytes: uuid.New(), Valid: true}

	_, err = r.store.CreateAuditEventWithPayload(ctx, db.CreateAuditEventWithPayloadParams{
		ID:               eventID,
		Region:           region,
		UserID:           userUUID,
		EventType:        string(et),
		ClientID:         clientID,
		PayloadEncrypted: ciphertext,
	})
	if err != nil {
		return fmt.Errorf("identity: audit: insert event: %w", err)
	}
	return nil
}

// RecordAsync fires Record in a background goroutine and returns immediately.
// Any write failure is logged at Warn level and metered, but never surfaced to
// the caller — keeping the audit trail from stalling the auth hot path
// (DESIGN §2.1, Decision 3). Use this at call sites on the hot path
// (/authorize, /token, /revoke).
//
// The caller's context is detached from its cancellation signal via
// context.WithoutCancel so the goroutine's DB write is not aborted when the
// HTTP handler returns (the request context would otherwise be cancelled
// before the goroutine has a chance to run). Trace/value propagation is
// preserved.
func (r *AuditRecorder) RecordAsync(ctx context.Context, userID string, et EventType, clientID *string, detail any) {
	detached := context.WithoutCancel(ctx)
	go func() {
		if err := r.Record(detached, userID, et, clientID, detail); err != nil {
			r.logger.WarnContext(detached, "identity: audit: best-effort write failed",
				"event_type", string(et),
				"error", err,
			)
		}
	}()
}

// RecordNoPayload appends a payload-less audit event (region, event_type,
// client_id, timestamp — all in the clear, no encrypted detail). Unlike Record
// it does NOT require the user's DEK, making it the only way to audit an event
// after the DEK has been crypto-shredded (e.g. compliance.erase_completed).
// The row it writes is exactly the pseudonymous survival set the design intends
// (DESIGN §compliance-export invariant 5).
func (r *AuditRecorder) RecordNoPayload(ctx context.Context, userID, region string, et EventType, clientID *string) error {
	userUUID, err := parseAuditUUID(userID)
	if err != nil {
		return fmt.Errorf("identity: audit: parse user UUID: %w", err)
	}
	eventID := pgtype.UUID{Bytes: uuid.New(), Valid: true}
	_, err = r.store.CreateAuditEvent(ctx, db.CreateAuditEventParams{
		ID:        eventID,
		Region:    region,
		UserID:    userUUID,
		EventType: string(et),
		ClientID:  clientID,
	})
	if err != nil {
		return fmt.Errorf("identity: audit: insert no-payload event: %w", err)
	}
	return nil
}

// parseAuditUUID converts a UUID string to a pgtype.UUID for use in DB params.
func parseAuditUUID(s string) (pgtype.UUID, error) {
	id, err := uuid.Parse(s)
	if err != nil {
		return pgtype.UUID{}, err
	}
	return pgtype.UUID{Bytes: id, Valid: true}, nil
}
